### ISSUE TITLE
Modgroup order check works only relatively to the first mod of the group

### ISSUE THREAD

**Issue by WeAreAllMadeOfStars** [TES5Edit/TES5Edit#428] opened 2017-09-17 07:07 UTC
Let's say I have a typical load order:
```
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Unofficial Skyrim Legendary Edition Patch.esp
```

I've created TES5Edit.modgroups:
```
[Lawful Good USLEEP]
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Unofficial Skyrim Legendary Edition Patch.esp
[Chaotic Evil USLEEP]
Update.esm
Unofficial Skyrim Legendary Edition Patch.esp
HearthFires.esm
Dragonborn.esm
Dawnguard.esm
```

When I run TES5Edit, both groups are available. I don't have "plugins are not in the correct order" message for "evil" group. It seems, TES5Edit checks not an order, but the simple fact second, third and further mods of the group are after first one in frmViewMain.pas:
```
k := Abs(Integer(sl2.Objects[0]));
for j := 1 to Pred(sl2.Count) do begin
  if Abs(Integer(sl2.Objects[j])) <= k then begin
    sl2.Clear;
    MessageGiven := True;
    AddMessage(MessagePrefix + 'plugins are not in the correct order');
    Break;
  end;
end;
```

**Comment by eFrysTon** [comment] 2018-07-16 07:56
This issue should be solved with the commit listed above.

**Comment by eFrysTon** [comment] 2018-07-20 06:09
I'll assume the issue is fixed and close it. Please let me know if you find it's still an issue in the latest release.

**Closed by eFrysTon** 2018-07-20 06:09 UTC
Labels: TES5Edit, question
