### ISSUE TITLE
[FO4] Copying CELL data into a file can cause landscape collision to be re-enabled when it shouldn't.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#691] opened 2019-04-18 19:11 UTC
I've run into a bizarre situation with Fallout 4. In the included files, the cell containing the Hopesmarch Pentecostal Church has 2 references the UFO4P edited. Users have reported to us that this generates invisible ground and they can't jump down through the roof of the church.

After some wrangling I was able to fix the problem by completely removing the entire CELL record (and all its children) from the file. I then redid the 2 edits in the CK using the PC copy of the patch, saved, and tested it. Sure enough, everything worked fine.

Then I loaded up xEdit and the PS4 copy of the patch. I removed the entire CELL from it, saved, exited. Loaded xEdit back up afterward with both the PC and PS4 patches. I copied the data from the PC patch back into the PS4 patch. Saved and exited again.

When I tested the PS4 patch to be sure it worked, I found that it did not. Other members of the patch team have been able to confirm that this result is consistent. PC patch works, PS4 patch does not.

So I cut both files down to just the cell with the 2 edits in it for each file and tried that. Sure enough, one works, the other doesn't.

I have included 2 screenshots to illustrate the issue, because even the CK can see that the landscape collision has been re-enabled on the broken file. It's the yellow grid that shows up in the hole in the church's roof.

I have no idea what's going on here, but the only thing I can tell for sure is that copying the data from a working file into one that doesn't have it results in the second file being broken. So xEdit is missing something we're not able to see. Unless it has something to do with the Version Control data since the "Version Control Info 2" field has a 0F in the working file, and 00 in the one that doesn't. It's the only visible difference I can see when comparing, and xEdit even shows the data size for the CELL record is one bit different somewhere. Fallout4.esm has the 0F in the VC2 data as well.

It does not matter whether the file is flagged ESM or not, I tried it both ways to rule that out.

xEdit also does not seem to break it if the CELL record already exists and the new data is added to it. So we have a way to work around this until the bug is identified and fixed. I'm using xEdit 4.0.2 as downloaded from Nexus.

For background, what's happening here is that Bethesda disabled landscape rendering in the northwest quadrant of the cell and then placed a bunch of statics to simulate the church being partially buried. The broken file is causing the collision data to reappear but not the visible landscape that would be associated with it.

[Landscape Collision Bug.zip](https://github.com/TES5Edit/TES5Edit/files/3095857/Landscape.Collision.Bug.zip)

**Comment by VlitS** [comment] 2019-04-19 00:22
Well, it definitely isn't caused by the missing version control info. I used a script to copy it from the working patch into the broken one, and the broken one is still broken while working works.

Interestingly, if you copy as override the CELL itself, the data size is 1084.
If you Copy as Override the REFRs, with the CELL being copied as a necessity, it has the same size as in yours (1161).

**Comment by Arthmoor** [comment] 2019-04-19 00:55
The Version Control info was only speculation since I can't see any other difference here. Maybe there's some data that's not being displayed because someone thinks it's not needed?

**Comment by VlitS** [comment] 2019-04-19 01:26
Considering that version control info 1 is used for determining when the game should break precombineds, it wasn't a bad guess. I thought it might actually be the problem until fixing it did nothing. 

I also tried making the file headers identical (in particular copying the "Transient Types" subrecord, to no avail. Copying as override into a brand new plugin also failed. Only visible difference between working and broken is the data size of the cell record, and you get the invisible collision.

**Comment by Arthmoor** [comment] 2019-04-19 03:34
Yes, and the bad part is that once you've done the copy as override and it creates the bad CELL record, the FO4 CK will not correct it. You have to completely remove it and do the edits all over again in the CK to fix it.

**Comment by ElminsterAU** [comment] 2019-04-19 04:30
Need to compare the size of the sub records to identity which one is different

**Comment by Arthmoor** [comment] 2019-04-19 05:17
How would I go about doing that? It's a difference of a single bit as far as I can see from what xEdit is showing me.

**Comment by ElminsterAU** [comment] 2019-04-19 07:36
Byte, not bit. And this:
```
Interestingly, if you copy as override the CELL itself, the data size is 1084.
If you Copy as Override the REFRs, with the CELL being copied as a necessity, it has the same size as in yours (1181).
```
Sounds like a lot more than 1 byte.

**Comment by VlitS** [comment] 2019-04-19 10:29
The Data size is 1161 vs 1163 if you copy the REFRs rather than the CELL itself. Arthmoor's version in that zip is 1161. 

So the size of the copied cell varies based on how it is copied in xEdit.

**Comment by Arthmoor** [comment] 2019-05-04 20:36
So I guess I need to ask again - what do I need to do to help this along? I have no idea how to find a 1 byte difference in something like this when xEdit shows nothing different in a side by side display.

**Comment by 3lric** [comment] 2019-06-21 04:58
The flag does exist for this in xedit, but i cant remember where.. tim-timman and I had this issue in a collab mod we did and he was able to fix it in xedit, the flag was unknown though, it was either that or a version setting. I remember it was a really dumb thing that ended up fixing it...

**Comment by ElminsterAU** [comment] 2019-06-21 05:21
I found the issue and have it currently fixed in my local codebase.

**Comment by ElminsterAU** [comment] 2019-10-15 17:39
this should be fixed in the commits referenced above (should already have been included in 4.0.2i)

**Closed as completed by ElminsterAU** 2019-10-15 17:39 UTC
Labels: bug

**Comment by Arthmoor** [comment] 2019-10-15 17:57
Confirming it's been fixed for awhile now. I actually thought this ticket was closed before.

**Comment by ElminsterAU** [comment] 2019-10-15 17:59
There was a longer time where I made changes only to my local codebase and released updates on the Discord, but the changes didn't get commited into this repo. The repo is finally completely up to date now and I'm going through all the issues to close or assign them as necessary.

Thanks for confirming it's fixed.
