### ISSUE TITLE
Problems with codepage tranlation

### ISSUE THREAD

**Issue by GBRPlus** [TES5Edit/TES5Edit#614] opened 2018-12-06 18:02 UTC
TES4Edit 3.3.10 BETA (C9BB14F9) starting session 2018-12-06 19:49:41
Using language: russian
Using general string encoding: 1252  (ANSI - латиница 1)
Using translatable string encoding: 1251  (ANSI - кириллица)

Have problem with russian translations, Some records still have wrong codepage (like makers refs)
This can be avoid by set -cp -general:1251    But this thing is a bug of string eccoding translation.

**To Reproduce**
1. Take any russian esp with markerref (must have name)
1. Load with edit with  -l:russian  
2. Check :)

![default](https://user-images.githubusercontent.com/26788026/49602663-a6464f80-f991-11e8-87f5-b7c2f1915b74.png)

![default](https://user-images.githubusercontent.com/26788026/49602710-cece4980-f991-11e8-8154-38fabbe55784.png)

**Comment by ElminsterAU** [comment] 2018-12-06 19:03
This issue should be fixed with the commit referenced above. It's currently scheduled to be part of release 4.0.0

**Closed by ElminsterAU** 2018-12-06 19:03 UTC

**Comment by ElminsterAU** [comment] 2018-12-06 19:14
Please check with 3.3.11a at https://discordapp.com/channels/471930020454072348/518048160526893057/520316833727905793 if the issue is fixed for you.

**Comment by GBRPlus** [comment] 2018-12-07 14:18
Its ok now, thanks

**Comment by ElminsterAU** [comment] 2018-12-07 14:23
Thanks for confirming
