### ISSUE TITLE
OMOD: Access violation when adding element to DATA\Attach Parent Slots

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#393] opened 2016-12-21 13:22 UTC
Adding an Attach Parent Slots element to an OMOD\DATA subrecord produces an access violation.

**Comment by zilav** [comment] 2016-12-21 13:28
Can't reproduce, works fine for me.

**Comment by fireundubh** [comment] 2016-12-21 17:10
Hmm.

Running the latest build through NMM.

Copying an OMOD record as an override or as a new record, and then adding an Attach Parents Slot element will **not** produce an access violation.

But adding an Attach Parents Slot element to an existing plugin **will** produce an access violation.

Maybe there's an actual access permissions violation occurring. No idea how to run FO4Edit as an administrator through NMM though, so I can't test that case specifically.

**Comment by zilav** [comment] 2016-12-21 18:01
"Mark Modified" OMOD record before editing it.
OMOD is quite complex one, I doubt we are ever going to try to fix this. Not a critical error by any means, especially with a workaround.

**Comment by eFrysTon** [comment] 2018-07-28 16:52
This should be fixed with the commit listed above.

**Closed by eFrysTon** 2018-07-28 16:52 UTC
Labels: DecodeRecord, FO4Edit
