### ISSUE TITLE
CRC32 sum in TES5Edit.modgroups breaks Mod Group functionality

### ISSUE THREAD

**Issue by WeAreAllMadeOfStars** [TES5Edit/TES5Edit#427] opened 2017-09-15 19:21 UTC
Hello!
So, I have two groups:
[Unofficial Skyrim Patch SUM]
Update.esm:18401373
Dawnguard.esm:50FB6A39
HearthFires.esm:FBB4B8FA
Dragonborn.esm:E0715431
Unofficial Skyrim Legendary Edition Patch.esp:13136E20
[Unofficial Skyrim Patch NOSUM]
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Unofficial Skyrim Legendary Edition Patch.esp

TES5Edit correctly checks sums and doesn't show group if some sum is wrong (logging it). But with sums it just doesn't work as intended:
"Apply Filter for Conflict Loosers" gives empty mod list after filtering, if I use NOSUM group.
"Apply Filter for Conflict Loosers" gives regular red-colored list of mods, if I use SUM group.
Lowercase of uppercase sum - no matter.

I am using FO4Edit 3.2-2737-3-2.7z from FO4 Nexus with binary renamed to TES5Edit, if it matters.

**Comment by Sharlikran** [comment] 2018-07-16 06:45
This should be fixed in d91bf5409bd8837e9a63873ed08d715797dc99fb which should be in the next version.

**Comment by eFrysTon** [comment] 2018-07-20 06:10
I'll assume the issue is fixed and close it. Please let me know if you find it's still an issue in the latest release.

**Closed by eFrysTon** 2018-07-20 06:10 UTC
Labels: TES5Edit, question
