### ISSUE TITLE
Invalid Parameter, VirtualTrees.pas

### ISSUE THREAD

**Issue by anakha3263** [TES5Edit/TES5Edit#570] opened 2018-10-30 17:06 UTC
**What is the version of xEdit you are using?**
TES5Edit 3.2.84 EXPERIMENTAL (2B66447C) starting session 2018-10-30 16:54:56

**Describe the bug**
Attempting to apply any filter to my modlist causes the following error:
[01:29] Error during Applying Filter: Invalid parameter. (P:\TES5Edit\VirtualTrees\Source\VirtualTrees.pas, line 15519)
This occurs with both the compare filter and the cleaning filter, with a large number of mods in list (up to 8C).

**Additional context**
Error logs attached for both SSEEdit and TES5Edit:
https://puu.sh/BTryC.log
https://puu.sh/BTry4.log

**Comment by Sharlikran** [comment] 2018-11-04 12:29
Please list the exact steps. When using apply filter you can only apply one filter so your statement makes me think you used apply filter for cleaning and then you are comparing something but I cant reproduce it.

**Comment by ElminsterAU** [comment] 2018-11-04 12:31
this is already fixed in the commit listed above and will be in the next release

**Comment by Sharlikran** [comment] 2018-11-04 12:31
That's what I wanted to test but of you feel that's not needed then never mind.

**Comment by ElminsterAU** [comment] 2018-11-04 12:32
I'm confident that I was able to identify the source of the problem based on a callstack I got from someone else.

**Comment by anakha3263** [comment] 2018-11-04 16:15
The steps I followed were the same I've done for the last few years:
Load the program,
Right click anywhere in the left hand pane,
Select Apply filter for conflicts.

The same method for the cleaning filter, although separately, as I am aware that you can't apply both at once. Though oddly the error went away when I removed JK's Skyrim from my load order

**Comment by ElminsterAU** [comment] 2018-11-05 10:08
This should be fixed in 3.3.0 BETA

**Closed by ElminsterAU** 2018-11-05 10:08 UTC
