### ISSUE TITLE
[FO4] Load order is being ignored

### ISSUE THREAD

**Issue by FenghuangZero** [TES5Edit/TES5Edit#926] opened 2021-05-30 13:21 UTC
**What is the version of xEdit you are using?**
FO4Edit 4.0.3g (4FC4B24D) starting session 2021-05-30 13:56:53

**Describe the bug**
Plugins are always being loaded according to timestamp, and entirely ignoring the loadorder.txt and plugins.txt settings. This results in an order that differs from what is loaded in game, and could result in confusion when attempting conflict resolution.

**To reproduce**
1. Use in-game Mod Management or LOOT to change Load Order, or manually edit plugins.txt or loadorder.txt.
2. Launch FO4Edit.exe and observe the Module Selection window.
3. See that Load Order does not match the order set in step 1, and is instead changed to match the file timestamp.

**Expected behavior**
For FO4Edit to read loadorder.txt to determine order of plugins.

**Screenshots**

![Screenshot 2021-05-30 141211](https://user-images.githubusercontent.com/17545518/120105491-0ed0aa80-c151-11eb-8ef6-a28744d2435f.png)

**Comment by ElminsterAU** [comment] 2021-05-30 14:06
Something is broken on your system. It works fine for 100000s of other people.

Check the top of the messages log to see what plugins.txt is being loaded, then figure out why yours isn't where it's supposed to be.

**Comment by FenghuangZero** [comment] 2021-05-30 16:36
> FO4Edit 4.0.3g (4FC4B24D) starting session 2021-05-30 17:28:46
Using Fallout4 Data Path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\
Using Backup Path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\FO4Edit Backups\
Using Scripts Path: D:\Program Files\xEdit\Edit Scripts\
Using Cache Path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\FO4Edit Cache\
Using ini: C:\Users\Chris\OneDrive\Documents\My Games\Fallout4\Fallout4.ini
Using save path: C:\Users\Chris\OneDrive\Documents\My Games\Fallout4\Saves\
Using Creation Club Content list: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Fallout4.ccc
Using plugin list: C:\Users\Chris\AppData\Local\Fallout4\Plugins.txt
Using settings file: C:\Users\Chris\AppData\Local\Fallout4\Plugins.fo4viewsettings
Using language: En
Using general string encoding: 1252  (ANSI - Latin I)
Using translatable string encoding: 1252  (ANSI - Latin I)
Using VMAD string encoding: 65001 (UTF-8)
Loading active plugin list: C:\Users\Chris\AppData\Local\Fallout4\Plugins.txt
[00:00] Background Loader: starting...

That's the same plugins file shown in the screenshot.

**Comment by FenghuangZero** [comment] 2021-05-30 17:28
Further testing confirms this issue occurs with version 4.0.3g only, and is not present in 4.0.3f or 4.1.3g.

**Comment by ElminsterAU** [comment] 2021-05-30 18:19
Can't reproduce it. But I'll schedule an in depth code review, might be an uninitialized variable somewhere or something like that.

let me point out one thing though: loadorder.txt is exclusively used for Skyrim LE. Because that is the only game where plugins.txt defines the order, but does not have a mechanism for marking which files are active or not.

Before Skyrim LE, order was defined by file dates, and active status by being included in plugins.txt

In Skyrim LE, order is defined by plugins.txt, and all files listed are active. Which is why loadorder.txt is necessary for tools.

After Skyrim LE (SSE, FO4, ...) order is defined by plugins.txt, and active status by which plugins listed start with a star. loadorder.txt is not needed and is in fact a really stupid idea to have it in these games as  you just end up with 2 different files with the same information which can conflict.

**Comment by Atlntssplayer** [comment] 2021-06-07 11:35
I have a similar issue. I first noticed it when I tried v4.0.3g but recently it also happened with v4.0.3f.
I run xEdit through MO2. I figure it's not a problem with MO2 because in the game everything seems to be working as expected and there is a mods/load order menu which shows the same order of my plugins as it is in my MO2 setup.

Here are some screenshots I made to try and demonstrate the problem.

This is the end of the plugin load order of my setup in MO2, this is the state I run xEdit from.
Notice that ThisIsTrash.esp has priority 468 and mod index 9A.
InteriorsEnhanced-All-In-One.esp has a priority 469 and mod index FE:13A
[https://ibb.co/LZ91fW9](https://ibb.co/LZ91fW9)

I run xEdit and in the module selection window the order of plugins as shown seem correct, same as in MO2 but the load order and formid prefix columns (which should be the same as priority and mod index in MO2's window) show an incorrect value.
[https://ibb.co/YZbJPQD](https://ibb.co/YZbJPQD)

Here is the end of the load order of plugins after they are loaded by xEdit.
ThisIsTrash.esp and InteriorsEnhanced-All-In-One.esp are not there at the end where they are supposed to be.
[https://ibb.co/0rgHPpt](https://ibb.co/0rgHPpt)

Instead they are at these incorrect positions.
[https://ibb.co/GQkLVKP](https://ibb.co/GQkLVKP)


Thank you for looking into this issue and for developing this awesome program!

**Comment by Infernio** [comment] 2021-06-07 11:53
@Atlntssplayer Those are almost certainly *not* incorrect positions. xEdit loads the order exactly the same way the game does, which means it pulls forward plugins if another plugin has them as a master and loads earlier (called *delinquent masters*). MO2 does not show you these, so you have to use a tool that does (e.g. in Wrye Bash you can look for orange checkboxes).

This issue is explicitly about a regression in 4.0.3g. The behavior you're seeing is not a bug at all, but expected behavior.

**Comment by Atlntssplayer** [comment] 2021-06-07 13:43
Thank you for your response. You were right. After re-sorting the masters in a few plugins and re-arranging them in my load order I now have the same order in MO2 and xEdit v403f.

xEdit v403g shows a completley different order though, but that is probably the bug that this topic was originally opened for.

**Comment by ElminsterAU** [comment] 2021-06-28 04:30
should be fixed with commit referenced above (will be in 4.0.3h)

**Closed as completed by ElminsterAU** 2021-06-28 04:30 UTC
