### ISSUE TITLE
[Skyrim LE/SE] Texture hash differences are wrongly assumed to be irrelevant

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#453] opened 2018-02-18 22:33 UTC
https://i.imgur.com/TusNCVe.png

Texture hashes change when mods in SSE convert properly to form 44, but since this data is possible to change in other ways as well they should be flagging these as edited records. Right now they're obviously being ignored and thus will show up as ITMs.

As we know, wrong record versions in these leads to CTDs, and that's apparently true in the case of forms from the masters in SSE as well if they're cleaned. Apparently not every exception was covered by Bethesda when they updated the code.

**Comment by zilav** [comment] 2018-02-19 05:59
Cleaning removes the entire record, not the hashes only. It will never lead to crashes in SSE as the game will simply use the original vanilla record whatever version and hashes it has. And any vanilla record by default is considered to be working.

**Comment by Arthmoor** [comment] 2018-02-19 20:08
I am well aware that cleaning removes the entire record, but the behavior is incorrect in this case.

The record should not be getting cleaned as it was part of a legitimate use of the CK to convert the mod for SSE use.

**Comment by zilav** [comment] 2018-02-20 05:59
Any vanilla record in vanilla master file is also legitimate otherwise Bethesda would have converted it before the release.

**Comment by Arthmoor** [comment] 2018-02-20 20:35
So is there some reason you're resistant to the idea of fixing this bug?

**Comment by zilav** [comment] 2018-02-21 05:50
What bug? You said that cleaning plugin saved in SSE CK will crash the game because it removes "part of a legitimate use of the CK". It is not true because the game will use vanilla records instead which are not less legitimate than the ones saved from CK, otherwise the whole game without any mods would have been a crash fest right from the start.

Give me plugin saved in CK which will crash SSE after cleaning, then I can at least start looking. Otherwise I don't have any idea of what I'm supposed to fix.

**Comment by Arthmoor** [comment] 2018-02-21 06:19
The difference in the texture hash. It makes the edit not an ITM. That field is clearly being marked to ignore in the record definition somewhere. Seems to me that it should be no more difficult to fix than any other such field that's come up before.

Specifically, the MO2T field. The way I see it the CK would not have updated it if it was not necessary for it to do so.

**Comment by zilav** [comment] 2018-02-21 08:26
Texture hashes are not important that's why Elminster made them ignored in conflicts resolution. The same in SSE despite the changed format.

Bethesda did not update hashes in vanilla files (mostly in records that have changes in binary structure like weapons since they had to make them version 44 and thus update the hashes too), a lot of them still use the old format because the game reads both equally well. They are both legitimate.

**Comment by Arthmoor** [comment] 2018-02-21 19:11
Eliminster was not perfect though and changes of this nature have been made before. You could easily have had it done and compiled by now even :P

Bottom line is this isn't an ITM and it's causing people to badger mod authors about it who then turn around and say xEdit can't be trusted or that they're intentional ITMs and neither case is true. They're not intentional ITMs and xEdit obviously just needs to be tweaked and this problem goes away.

**Comment by zilav** [comment] 2018-02-22 06:14
ITM records are not binary identical ones, but those that have the same effect in the game. That's why xEdit has some fields marked to be ignored for conflicts resolution.

Texture hashes never affected any of Beth games since Oblivion (this has been proved by 10 years history of xEdit and plugins cleaning), and SSE is not any different despite their format change. Removing or not removing that record on your screenshot changes nothing, hence it is an ITM record in that sense.

The whole purpose of cleaning is to remove as many records as possible without having any effect on the game to reduce the amount of possible conflicts. Unless you can provide a test plugin with changed hashes which does affect the game somehow, I don't see any reason to update xEdit. But such plugin will definitely change my nature :)

And mod authors should clean their plugins before uploading themselves, then users won't badger them. It is a golden rule of modding, since when did it change suddenly.

**Comment by Arthmoor** [comment] 2018-02-22 06:56
So you see no reason to fix incorrect behavior? I don't get that. I really don't.

Yes, mod authors should clean their plugins. Except when xEdit is producing invalid results. You're resistance to fixing this is making me lose trust in using the program at this point. I'm not sure that's such a good thing to be doing.

**Comment by zilav** [comment] 2018-02-22 07:29
Why is it _incorrect_? As I said such records fall under the definition of ITM records because of having no effect on the game, so xEdit has all the rights to remove them and lessen the amount of possible conflicts with other mods. This is the ony purpose of cleaning.

It is me not getting why are you pushing for not removing such records when you know yourself that they are meaningless. And you know that, right? Because if not, then you can easily replicate a problem with a test plugin where hashes in new format are critical for the game.

So CK added some records to plugin when not asked? Big news - official editors adding useless crap in plugins. Cleaning was implemented to circumvent this problem of official editors in the first place. The only difference is that SSE CK has one more reason to dump more crap in plugins compared to the previous games  - form version updating of records which don't need that at all. Some do of course and Bethesda updated them in vanilla files, but some don't and they left them as is like in original Skyrim. The record on your screenshot is one those that don't need updating, hence this updating does nothing in the game, hence it is an ITM record, hence it can and should be removed.

**Comment by zilav** [comment] 2018-02-22 07:31
Should not close it, will be waiting for a proof plugin with meaningfull hashes in the new format affecting the game in any way.

**Comment by Arthmoor** [comment] 2018-02-22 19:03
It's incorrect because it's incorrect. Does there seriously need to be a PhD written on the subject to convince you of a genuine error? I REALLY do not get this resistance. The data is not identical in a relevant field. It's not like I'm asking you to do something about the version control field or something. So no, I do not consider this a meaningless request or I would not have filed this issue to begin with. I think you are misinterpreting what cleaning is supposed to be used for and if this kind of thing is going to start being ignored, you shouldn't be surprised when mod authors start telling people never to use xEdit because it can't be trusted. I already see this happening, and this kind of thing is why.

It's not an ITM. Period. That should literally have been all I needed to show you. This whole discussion should never have needed to take place. No wonder fireundubh felt it necessary to fork the project at one point.

**Comment by warmfrost85** [comment] 2018-02-22 22:02
This looks like a continuation of a conversation at Wrye Bash. :)

_I, a mere mortal, will give an opinion to the gods of modding. May the gods not send a lightening bolt at me._ 

Sounds like the issue is mod authors don't re-save their plugins in the CK, then when the plugin is cleaned the hashes record is marked as ITM (to increase compatibility with other plugins), users then blame xEdit (incorrectly) for marking it as ITM. Trying to fix the ITM issue is fixing the symptom not the disease. It enables mod authors to be lazy. IMHO, it is not the responsibility of xEdit or Wrye Bash to attempt to compensate for mod authors ineptness. Protect the user yes and that is what zilav has done by marking the record as ITM. It may not be the perfect solution but it is one of many approaches and the one zilav has chosen until someone can convince him otherwise.

>Eliminster was not perfect

Even the gods aren't perfect.

**Comment by JohnsonNicholas** [comment] 2018-02-22 22:04
It *literally is not an ITM*. It doesn't matter what people think. It *is not an ITM*

**Comment by Arthmoor** [comment] 2018-02-22 22:06
@warmfrost85 The only problem is, this mod was correctly saved in the CK and has proper form 44 formatting everywhere. The 4 ITMs it reports are 100% false. They are not identical because the texture hashes do not match. Those records are relevant and should not be getting stripped out.

**Comment by warmfrost85** [comment] 2018-02-22 22:24
Oh, it was saved in the CK. I misunderstood. Hmmm. 

If the only difference between two plugins is the texture hashes, they are considered ITM because hashes are ignored in that comparison? If so, you're saying they are not ITM because of they have  different texture hashes. Zilav says they are ITM because xEdit has always ignored text hashes and ignoring them doesn't affect game stability.

**Comment by Arthmoor** [comment] 2018-02-22 23:42
Yes. Except using the logic of "but it's always been done this way" doesn't apply well to SSE. We already know this from various form 44 situations that come up for other things, like the Bashed Patch.

Ignoring a relevant data field is wrong, period. This isn't like other stuff we've been able to clearly demonstrate doesn't cause issues when ignored.

**Comment by RoyBatty64** [comment] 2018-02-23 06:59
Does the game even use the hashes? They are probably only used for VC and you shouldn't be touching plugins with xEdit or any other tool if you are using VC in any way because VC information is not preserved. "Because I said so" is not a valid argument without something to back up your claim.  Surely it's easy to get hlp or Expired to examine the game code and see if that is the case or not. Many fields are useless and unused and should be ignored whether or not CK modifies them, this is well established. Or you could always get IDA 7 and learn to do it yourself instead of making claims based on opinion.

If you have insider information about it then share it, if you are under NDA then you shouldn't bring it up anyways.

zilav and the team have always changed things with evidence that something is incorrect.

Making veiled threats and being hostile is also rude to the developers, counterproductive and serves no purpose.

**Comment by zilav** [comment] 2018-02-23 14:01
Alright, I made a mistake. A mistake that I didn't check records myself and made a conclusion about new hashes format judging only by a screenshot of GRAS record (in bashed patch crashing the game) from xEdit which compared versions 39 and 44.

I asked Hlp to check the "new" and old hashes format (how the game actually reads them), and turned out that the format is not new at all and records with version >= 40 have it even in Oldrim. So the switch to the new hashes format occured even before the original release of the game in 2011 because it had version 40 records right from the start (and yes, they do have hashes in the new format, checked that myself now to confirm).

Since "new" hashes are not related to SSE in any way as we know for sure, and since "SSE is different" argument no longer applies when the only binary change in a record are hashes, the case is closed. Such records are ITM and should be removed.

**Closed by zilav** 2018-02-23 14:01 UTC

**Comment by Arthmoor** [comment] 2018-02-23 20:12
No, they're not ITM, and it doesn't matter what kind of twisted logic you're using to arrive at that conclusion. The data is clearly different and should not be treated as though it isn't. The resistance to fixing this issue is mind boggling at best and worrisome at worst. All you've done now is discouraged anyone else from reporting legitimate issues in the future and I myself now know not to waste my time doing so again. You do a serious disservice to the entire community by ignoring legitimate issues like this.

**Comment by zilav** [comment] 2018-02-24 06:55
Twisted logic? Mind boggling? Worrisome? Waste of time? Serious disservice to the the entire community? Please stop throwing heavy words and calm down.

Do you understand that you claiming "The data is clearly different and should not be treated as though" basically means that the whole plugins cleaning process was a mistake for the past 10 years since Oblivion? ITM records are almost NEVER binary indentical. Green in xEdit doesn't mean binary identical, it means no conflicts affecting the game.

Texture hashes have always been ignored when cleaning because they don't affect the game. So all the cleaned Oblivioin mods including DLCs, UOP and mods on the Nexus are broken? All the cleaned Skyrim mods including USLEEP are broken too? Dozens of thousands of people playing with cleaned plugins broke their games? This is what you are trying to prove here right now? If so, then open a thread on afkmods to discuss the technical aspects of the cleaning process, we'll talk there if you wish so.

**Comment by Arthmoor** [comment] 2018-02-24 20:35
If we were discussing Oblivion, FO3, NV, or even regular old Skyrim I'd be right there with you since those games don't do anything significant with those hashes. In fact I even recall having lobbied Elminster to get the original code put in for Oblivion to ignore them precisely because we proved they didn't matter back then.

That's where your logic fails. You are assuming that SSE doesn't do anything with them, but we know for absolute fact that not only does the game read them, but them being wrong will cause CTDs. Multiple mod authors have confirmed this, and that's the main reason I asked for this particular subrecord to get removed from the ignore list for SSE. SSE is the only game I have evidence for that it causes a problem. So this should have been a straightforward easy fix, but you turned it into a ridiculous argument instead.

Right now, with this being done, I've been told (still waiting on the list) that 28 records in the official master files are ALSO being wrongly stripped out of the files. If this is the case then it would begin to explain why experienced mod users and other authors alike have been floating the idea that cleaning the official files is causing instability in the game. Resistance to the standard advice of old has been very high for SSE and it's only now that I'm starting to see the proof as to why.
