### ISSUE TITLE
xEdit Feature Request: Option to change master when loading a plugin with a missing master

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#283] opened 2015-12-13 06:28 UTC
Instead of disabling editing when loading a plugin that has a master that can't be loaded, can xEdit instead, or in addition, provide an option to change that master to another one?

Back when I was modding Skyrim, and especially now with the explosion of modular installs for Fallout 4, I find that I'm having to constantly merge plugins. Of course, this also involves a file name change, which of course means that any patch plugins will have to be updated to the new master file.

Currently, you have to load both the merged plugin and the original modular plugins, in addition to the patch plugins, and then edit the master name in the patch plugin headers. This process could be made much smoother, faster, and more intuitive if xEdit, instead of simply disabling editing, would also provide the user the option of changing the missing master to an existing one.

This option could be as simple as loading the plugin with the missing master anyway, instead of throwing a fatal error, while disabling the ability to edit any part of any plugin except the file header of the plugin with the missing master. In this case, you'd still have to reload xEdit because I don't think xEdit has the ability to hot reload a new set of plugins without exiting, but you'd cut down the number of xEdit restarts by at least one, and that's more convenient than the current process.

**Comment by zilav** [comment] 2015-12-13 06:48
Wrye Bash has an option to create empry missing masters for a plugin. Changing how xEdit loads plugins is not that easy since it uses memory mapped files.

**Comment by fireundubh** [comment] 2015-12-13 07:54
Why not read the plugin headers before anything else and do a preliminary check for missing masters? If there are any, you can pop up a warning followed by a dialog with which you can change missing masters to ones that are not, and then continue executing xEdit operations as normal.

That's a bit more involved than what I was requesting though.

I also didn't think about using empty plugins for missing masters. That's a good idea.

**Comment by zilav** [comment] 2015-12-13 10:32
This will require adding notification callback events to IwbFile. While possible, it is not on my list of things to do first. Maybe later.

**Comment by Hugues92** [comment] 2015-12-13 11:47
I totally disagree. There are enough people doing stupid things with xEdit without hiding such a major issue from them. Imagine someone asked to clean a file and who does that without installing all the masters.
In order to change a missing master you need to use a tool that doesn't make any use of the masters.
For example, auto replacing missing master with an empty one is available in the save branch of dump, but only because this is an extraction tools. No change would happen to the original file.

**Comment by Sharlikran** [comment] 2015-12-14 16:26
I also discourage this because of how the FormID prefixes are assigned to the masters.  When you replace the original master with a new one, depending on the changes, you could create an unresolved reference.

As far as overrides go I usually quote Elminster.  "If a plugin has two masters that are siblings (one doesn’t have the other as a master, so they can load in either order) and they are overriding the same record from an earlier master (e.g. both are overriding a record from the main game master file), then loading them in a different order will result in a different version of the overridden record being the “winner”. But the plugin might depend on the winner being the one indicated by the order in which it references the masters."

Proper overrides are assigned to the specific master in the order in which the masters appear.  Replacing a master with a new one may not change the order of the masters but could invalidate what the author intended the override to do.

**Comment by RoyBatty64** [comment] 2015-12-14 16:40
Why don't you make expert features available to people who use the -IKnowWhatImDoing switch and keep them hidden for the masses. I've suggested this before so expert modders can have some extra functionality in the tool. Bad modders are going to make bad mods not matter what, not a valid argument.

**Comment by Sharlikran** [comment] 2015-12-14 17:25
@RoyBatty64 I understand additional advanced features could be beneficial to more experienced uses of xEdit like yourself.  However, the issue isn't whether or not bad moders will or won't make bad mods.  This ticket is a request to add the option to change a master when loading a plugin with a missing master.  Please post comments and responses that are only in regards to the issue or feature request.

**Comment by fireundubh** [comment] 2015-12-14 19:23
> I also discourage this because of how the FormID prefixes are assigned to the masters. 

While you generally shouldn't screw with masters directly in the plugin header, there are times when you can do this safely. For example, when you merge plugins without renumbering Form IDs and then need to update compatibility patches to the new master (and there's only one) is one of those times.

**Comment by RoyBatty64** [comment] 2015-12-14 19:56
I only made the comment because I would find such a feature useful. Like fireundubh suggested, when updating patches where the formid's have not changed but the plugin name has changed. Instances include patches for CoT , USLEEP, and the forth coming New Vegas Uncut which is based upon Freeside Open.

**Comment by Sharlikran** [comment] 2015-12-14 20:35
Yeah but see you are both making good points and I respect both of them.  I kept rewording my response to be as respectful as I could.  I really like seeing good suggestions like this.  However, I don't usually see people post comments on the Nexus and elsewhere when things are done correctly, I see the aftermath because people didn't do something correctly.

Most novice users feel if the feature exists then they should be able to use the feature how they want and not how we intended it to be used.  Take issue #208 for example.  The users original post was that he was trying to merge mods and in doing so discovered that when you try to renumber all the FormIDs in an entire plugin it doesn't work.  It might work for 10,000 FormIDs and it might work when WRLD and CELL records are not involved.  He gave some example plugins and I agree the FormIDs should be renumbered correctly.  However, getting the FormIDs to be renumbered properly is an ulterier motive.  Once it's fixed he wants to merge mods.  What if something else doesn't work.  Then he will say this is a valid thing that also needs to be fixed.  All the while because he is merging mods.

If Zilav adds this feature once the two of you test it then the two of you will use it and it will do what both of you need.  Both of you know what to do once you change the master.  However, people will use it incorrectly and then complain when it doesn't do they want.  When we explain it is intended to be used simply to change the name of the master and after changing it authors have to take the time to manually fix the plugin.  The responce will be that users should be warned and it should be in documentation and all the usual stuff.

In my mind it's just hard to satisfy advanced users valid requests and keep them idiot proof for novice users.

**Comment by RoyBatty64** [comment] 2015-12-14 21:53
I meant no disrespect, let be clear on that. :)

You know as well as I do that it's impossible to idiot proof a powerful utility, they will find some way to use it incorrectly. What do those idiots even use it for anymore anyways? cleaning? Wouldn't it be easy to make a stand alone "idiot" tool for that which uses the rules from LOOT? Wrye pretty much covered making patches now, especially if people use fire's tag script. Mator is making his tools stand alone now.

**Comment by fireundubh** [comment] 2015-12-15 06:54
> I don't usually see people post comments on the Nexus and elsewhere when things are done correctly, I see the aftermath because people didn't do something correctly. [...] In my mind it's just hard to satisfy advanced users valid requests and keep them idiot proof for novice and lazy users.

You can't satisfy everyone's needs with a single build of xEdit and trying to do so only means hamstringing the feature set for *all* user groups. Nobody else who makes advanced software for advanced users tries to cater to novices at the expense of advanced users. When they want to directly support novices, what they do is create a separate build, narrow the number of use cases, and simplify and streamline the user interace and feature set. Perhaps we need two xEdits: xEdit Basic with a wizard for cleaning and some easy conflict resolution solutions; and xEdit Pro, which is what we have now.

**Comment by Sharlikran** [comment] 2015-12-15 08:26
Nobody meant any disrespect and I appreciate all the kind input and feedback.  I got a little long winded but I had a hard time trying to say what was one my mind and still be as respectful. Especially toward people I like communicating with.

We will just have to wait until later when Zilav has time as he mentioned.

**Closed** 2018-07-28 17:36 UTC
Labels: Enhancement
