### ISSUE TITLE
[Feature Request] Enough plugin indexes for 4096 ESLs

### ISSUE THREAD

**Issue by EnmaPlays** [TES5Edit/TES5Edit#455] opened 2018-03-24 12:20 UTC
# Background
In order to work with the FF limit for mods, I've been converting as many of my plugins as possible to the new ESL format when it makes sense. All ESLs are loaded in slot 0xFE at runtime and have their own load order within that slot designated by the next three digits. I.e. the 10th ESL would be 0xFE00A. Bethesda also reserves some space for the Creation Club. It is now possible to have up to ~ 4351 plugins (255 8-bit slots, some being reserved, plus up to 4096 ESL plugins.)

# What Goes Wrong
In release 3da194b, it seems the ESL load order is simply translated into 8-bit. This works fine as long as the total number of plugins is under the 8-bit limit, but now that people can exceed that number by around a factor of 17, that isn't going to work. For example, if I try to load 200 ESLs and 100 ESPs, xEdit will complain and I have to do the dance of trying to work in batches. It is quite tedious.

# What's Expected
Vortex sorts these as FE(#) where # = ESL load order. LOOT marks ESLs with a new symbol. I'm not sure what they're doing internally. xEdit load order should be consistent with these tools.

**Comment by zilav** [comment] 2018-03-24 14:21
Mod managers don't have to deal with plugin's content so they can freely assign whatever numbers they want. xEdit has to and each plugin requires a separate slot, at least for now.

**Comment by EnmaPlays** [comment] 2018-03-25 01:27
That's fair, but the bug still stands as xEdit only has the original 8-bit budget of slots and that no longer represents the maximum plugin count allowed by the engine. The engine in FO4 and SSE will now load the original 255 ESM/ESP as we're all used to **PLUS** up to 4096 ESL plugins.  Doing conflict checks is much more difficult when the whole load order can't be loaded at once. This seems like a critical flaw to me.

[https://www.creationkit.com/fallout4/index.php?title=Data_File#Light_Master]

**Comment by zilav** [comment] 2018-03-25 05:48
This is not a bug, each plugin must have unique index to identify it's records when working with them. CK won't load ESLs in a single slot for the same reason too (if it can even load them at all). This is irrelevant to what the game engine does because xEdit and CK are editing software, not games.

**Comment by EnmaPlays** [comment] 2018-03-25 07:10
Yes, each plugin must have a unique index. ESM/ESP use ##xxxxxx where ## represents the plugin's index and the following 6 digits are for forms within that plugin, yeah? What ESL does is take the FExxxxxx identifier and reserve the next following three digits for a sub-index for lack of a better word, FE00A would be the 10th ESL plugin. FEDAC uould be the 3500th ESL plugin. ESL's are named 'light' because, with those three digits stolen, they only have the last three for their own use and the lower half are reserved (800-FFF are usable.)

The order the engine is going to load these is relevant to xEdit because the Rule of One. If xEdit didn't accurately load plugins in the same order that the engine will, there would be no sane way to evaluate conflicting records. 

It gets a little messier since they aren't loaded strictly in lexicographical order anymore. That would put ESLs at the end of the load order, but that's not what happens. I fixed the link above which has a little bit of background information. 

xEdit does just fine by seemingly reading plugins.txt and labeling them 00-FF, but that is no longer sufficient since the total number of plugins can now be around 4350 instead of 255.  You'd need at least a 20-bit identifier to continue doing it in that way (0000-FFFF = 65536 assignable IDs.) That would be the simplest solution.

One of the most common tasks I use xEdit for is to check a new mod I've found against my load order to look for conflicting records. Sometimes it is possible to make an educated guess at which ones may be relevant and exclude the rest, thus reducing the number of plugins xEdit must load at once, but it isn't always self-evident. Regardless, I'm sure you would concur that being able to load your whole load order then use various filters like the conflict filter against it would be a valuable feature of xEdit. That takes human error and guess work out of the equation and makes for an overall improved user experience. 

As for the word 'bug' perhaps you'd prefer another word. Call it a feature request if you like. Regardless, I'm sure you'd agree it is an issue worth tracking and working towards.

**Comment by zilav** [comment] 2018-03-25 10:15
I know how ESLs work, but xEdit doesn't support that. And I'm not going to implement this any time soon myself because I have other more interesting things to do.

**Comment by EnmaPlays** [comment] 2018-03-25 10:39
Fair enough. I get that it is a volunteer project (thanks for spending time on it at all for that matter!)

I see there are other open feature requests going back years. I'm not going to twist your arm to have this as a development milestone or anything, but would you concede to at least re-open it as a feature request and leave it there on the back burner? Perhaps another contributor or even a benevolent anonymous community member might see it and submit a pull request.

**Comment by eFrysTon** [comment] 2018-07-13 15:18
Elminster here... 

Given that load order corrected FormIDs are ephemeral (they only exist in variables, never stored in the bytes that make up the actual records) it should be possible to support > 255 plugins "relatively" easy by changing FormIDs from Cardinal to UInt64 and LoadOrder (in the few places where it's still a Byte) to Integer. 

The IntToHex64 calls for FormIDs could then be changed to use 9 instead of 8 digits, which enables 4096 modules in total. (And for LoadOrder from 2 to 3 digits).

This is purely theoretical, I haven't done an in-depth analysis if there are any issues with this approach.

I think there are some places where FormIDs are stuffed into Objects[] of TStringLists. But this would be a non-issue if xEdit is compiled as 64bit, which becomes essential anyway if you want to load that many plugins.

But it should be a lot easier then trying to load all the ESLs into the FE load order and deal with all the complications that produces.

**Comment by zilav** [comment] 2018-07-13 17:17
Nice too see you back :)

Mator is already experimenting with loading of > 255 plugins by replacing cardinals with Int64, changing Byte to Integer when passing load order indices, etc.

**Comment by eFrysTon** [comment] 2018-07-14 00:37
After having slept on it for a night, I've had an idea how to make this change in a way that the compiler will help finding all places where FormIDs are used, to make it impossible to overlook any places where Cardinals are being used to store it:

- Rename the TwbFormID in wbInterface to get it out of the way [purely exists in implementation section, so not a problem]
- Define a TwbFormID record containing an (U?)Int64 (which isn't going to be directly assignment compatible to/from Ordinal types)
- Change all interface methods in wbInterface that take or return FormIDs from Cardinal to TwbFormID.

The compiler will now error everywhere where code needs to be adjusted.

Instead of calling IntToHex64 or StrToInt explicitly everywhere, appropriate methods (either ToString/FromString methods, or maybe explicit[implicit?] assignment operators to/from string) can be added to the record.
Similar for reading/writing the LoadOrder part of the FormID, comparing them, or anything else that needs to be done to a FormID.

This will isolate all the code working on the internal representation of FormIDs in a single place instead of spreading it all over the code.

The main thing I'm still unsure about is how this will end up interacting with the scripting stuff (as I haven't been involved with that at all so far).

If I find the time, I might look into implementing this over the weekend...

**Comment by zilav** [comment] 2018-07-14 05:21
Thanks, that would be nice to have xEdit updated for big load orders.

Scripts usually use Cardinal for dealing with FormID numbers, however JvInterpreter doesn't have built-in type for it and uses Variant internally, so if functions dealing with FormIDs will start return UInt64 instead of Cardinal they should work without any changes. 

The worst thing that could happen is some scripts won't work correctly for plugins loaded at indices > 255 if they used Integers, but they already don't work correctly for plugins > 128 so they won't become worse either. Scripts are mostly used by mod authors and advanced users to solve specific problems and they don't load the entire load oder.

**Comment by eFrysTon** [comment] 2018-07-14 05:42
I've gotten quite far with it by now (though not yet at the point where I can compile again).

The biggest issue I've encountered so far is with wbLOD. Clearly, as that involves saving load order FormIDs to disk, this is not going to work correctly if ESLs aren't loaded into exactly the same FormIDs as the engine does.

For now I've simply mostly left that code untouched, and it's bound to fail when it encounters > 255 modules.

**Comment by zilav** [comment] 2018-07-14 06:51
Tree LOD can be generated as a part of the Objects LOD to workaround that, not a big problem. Can either put a warning in xLODGen's description or even force "Trees as Objects LOD" option when > 255 plugins loaded.

**Comment by eFrysTon** [comment] 2018-07-14 09:05
I'm not sure what place the in the load order ESL are loaded at, but if it's not always after everything else, then loading them as "full" modules instead of into FE will change the load order of all later loaded modules compared to what the game engines does, resulting in different load order Form IDs between xEdit and game engine starting from the first loaded ESL. 

So you probably need to force the "Trees as Objects LOD" option the moment any none-ESLs have been loaded after an ESL. Even when it's less than 255 modules in total.

**Comment by zilav** [comment] 2018-07-14 10:56
The whole Tree LOD system is a mess. I believe the game actually uses only the raw 24-bits number without the load order index (the reason why tree LOD doesn't work for trees with duplicate numbers even if they are in different plugins), and when the matching ref is found it gets the high byte and treats it as a master index of a ref's plugin masters, so the stored FormID is actually a FileFormID, not LoadOrderFormID.

However when I tested tree LOD generation long time ago, I got stuck LODs with FileFormIDs and only saving LoadOrderFormIDs worked fine. No idea why. Also load order index of any plugin will always be larger then the internal master index of new records in it, so when clamped (and I'm sure the game does that) LoadOrderFormIDs for newly added trees always match their FileFormIDs anyway.

CC is out for almost a year and noone have reported any issues with Trees LOD generation so far. I probably need to switch to FileFormIDs and test LODs again, maybe they fixed something in the Special Edition engine.

**Comment by Arthmoor** [comment] 2018-07-15 18:56
Did some poking around with ESL files that override vanilla forms. Results here: https://afkmods.iguanadons.net/index.php?/topic/5079-plugin-files-and-you-esmeslesp/&do=findComment&comment=173565

**Comment by eFrysTon** [comment] 2018-07-15 22:34
Just an update, I stepped back from supporting >255 "full" plugins, but the code changes I made for that incidentally allowed me to more easily implement "proper" support for "light" plugins (giving their records load order corrected FormIDs in the FE xxx namespace).

The actual loading and such seems to work fine. The last thing I need to make sure is that xEdit shows the modules where you can select them for loading in the same order as the game engine will use.

**Comment by Arthmoor** [comment] 2018-07-15 22:36
In case it's of use, there's also some info at the CK wiki: https://www.creationkit.com/fallout4/index.php?title=Data_File

ESL rules for FO4 are the same as for SSE.

**Comment by eFrysTon** [comment] 2018-07-16 04:12
Full support for ESL handling should be available in df8b8a20afc1afeca4844f2f11efb73524b0383e 
Determining the correct load order might need some more tweaks.
Any feedback would be appreciated.

**Comment by eFrysTon** [comment] 2018-07-26 18:29
Not having heard anything about ESL handling not performing correctly for 11 days, I'll assume this is done and close the issue....

**Closed by eFrysTon** 2018-07-26 18:29 UTC
Labels: Enhancement
