### ISSUE TITLE
UI update issue

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#368] opened 2016-06-30 23:08 UTC
I keep coming to post bugs, but it ends up being the UI update issue I've reported time and time again.
Collapsing and expanding the plugins after running scripts or doing certain actions never updates the UI, this puts a real damper on the work flow when it's thought an error occurred but the process actually completed. The only solution is to reload the plugin(s) which can disrupt or render the work unusable.

**Comment by zilav** [comment] 2016-07-01 05:45
Because it uses VirtualTree to display plugin structure where nodes doesn't exist and a chance that some records are not even parsed yet until you browse the tree. It is a minor downside of xEdit being blindly fast when loading millions of records in a few seconds imho.
I prefer speed with some manual refreshing/reloading when needed over dead slow automatic parsing/updating after every action.

**Comment by RoyBatty64** [comment] 2016-07-01 13:35
Yes I know that, you've explained it before. What I'm saying is, it breaks and never updates the records again after some actions. No amount of collapsing and expanding the tree updates the UI.

**Comment by zilav** [comment] 2016-07-01 15:35
I could never reproduce such issues myself, so can't say anything. Records tree branches always refresh for me when reexpanding. Some operations like moving records between parent groups and updating masters require reloading to be safe.

**Comment by eFrysTon** [comment] 2018-07-28 17:21
The navigation treeview can be in one of the states:

a) no filter applied, in this case only the visible nodes exist. The moment a node is collapsed, all child nodes are freed, when a node is expanded, the now visible child nodes are created at that moment based on the current information from the file. In this state, it's relatively easy to invalidate the tree, as it only contains maybe a few 100 nodes, and rebuilding the tree takes fractions of a second.

b) a filter has been applied, a major part of the work applying a filter does is actually build that whole tree, up to millions of nodes, at the time the filter is being run. The tree is now static, collapsing nodes does NOT free any child nodes. In this mode, it's impossible to invalidate the tree, as rebuilding it basically means a, sometimes multiple minute long, re-running of the filter. And you don't want to have that done automatically every time you edit a value somewhere.

No matter if the treeview is in state a) or b), if it is out of sync, all you have to do is select "Remove Filter" from the context menu, which will remove all nodes from the tree, put it into mode a) and re-add the nodes representing the files. 

The tree is the build on-demand using up-to-date information as you expand nodes.

Or you can apply a filter again, which rebuilds the tree from scratch, again, using up-to-date information at the moment the filter is run.

I don't think there is anything to fix here, so I'll be closing the issue.

**Closed by eFrysTon** 2018-07-28 17:21 UTC
Labels: Unexpected Behavior, User Interface
