### ISSUE TITLE
access violation when holding delete

### ISSUE THREAD

**Issue by yggdrasil75** [TES5Edit/TES5Edit#718] opened 2019-07-26 22:13 UTC
**What is the version of xEdit you are using?**
SSEEdit 4.0.2 [Auto Load] (F796EF8E) starting session 2019-07-26 16:51:52

**Describe the bug**
when holding delete on elements in a record to delete several, I get a messages "Access violation at address 00C0617 in module 'SSEEdit64.exe', Read of address 00000000.
**To reproduce**
1. Go to a record (discovered in weather records)
2. Click on a weather type
3. hold delete button

**Expected behavior**
delete several elements

**Comment by ElminsterAU** [comment] 2019-10-15 16:59
could not reproduce in 4.0.2i
could you please try yourself? If you can reproduce it, please supply an exception log. TIA!

**Comment by yggdrasil75** [comment] 2019-10-15 17:17
I was able to reproduce the error. I will note that it does take a moment to show.
[SSEEditException.log](https://github.com/TES5Edit/TES5Edit/files/3730615/SSEEditException.log)

**Comment by ElminsterAU** [comment] 2019-10-15 17:23
```Current Window Caption: SSEEdit 4.0.2```
That doesn't look like 4.0.2i

**Comment by yggdrasil75** [comment] 2019-10-15 17:28
woops, you are correct. 4.0.2i has a different exception:
[SSEEditException.log](https://github.com/TES5Edit/TES5Edit/files/3730650/SSEEditException.log)

**Comment by ElminsterAU** [comment] 2019-10-15 17:33
Thanks. While the line numbers make more sense now, the callstack itself is annoyingly uninformative. I'll have to ruminate on this a bit and see if I can come up with something.

Do you get this error with only the DLC loaded? what exactly are you deleting?

**Comment by yggdrasil75** [comment] 2019-10-15 17:37
I do get the message with only the dlc loaded, and while the previous messages have only occurred in weather records, I have just tested in a leveled list for dragonborn and gotten the same message.

**Comment by ElminsterAU** [comment] 2019-10-16 11:45
should be resolved with the commit referenced above (which should be in 4.0.2j)

**Closed as completed by ElminsterAU** 2019-10-16 11:45 UTC
Labels: bug, Can't Reproduce
