### ISSUE TITLE
AccessViolation while attempting to view Armor records in Fallout 4.

### ISSUE THREAD

**Issue by Yagisan** [TES5Edit/TES5Edit#351] opened 2016-04-19 12:26 UTC
Using FO4Edit 3.1.3 - 8eb0b5b.

I have been creating a compatibility patch for several power armor related mods. When I select the armor record it displays the first 6 records before crashing with an access violation. I have attached the produced TES5Edit bug report, although I am not sure how helpful that will be. I have been able to duplicate the crash upon examining the armor record in other mods, although it is inconsistent.

[TES5Edit_bugreport.txt](https://github.com/TES5Edit/TES5Edit/files/225820/TES5Edit_bugreport.txt)
[FO4Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/225846/FO4Edit_log.txt)

If there is any further information you require, please let me know.

Regards,
Yagisan

**Comment by zilav** [comment] 2016-04-19 13:13
Probably errors in those armor related mods since I don't get any errors when browsing vanilla armors including DLC.

**Comment by Yagisan** [comment] 2016-04-19 15:52
After some quite extensive testing, each of those armor mods works perfectly fine in isolation, and in small groups. When together in that specific combination, I trigger an Access Violation.

Given that small groups seems to work, I'll just eliminate unnecessary mods and recreate the patch - however something is triggering this bug.

I'd be happy to test a full debug enabled build if that can give you a better backtrace.

**Comment by Sharlikran** [comment] 2016-04-20 15:44
I don't know if that is contributing to this but any weapon and armor mod at one point had data in OMOD that shouldn't be there.  I had posted this elsewhere but I'll add it here.
![needsupdated](https://cloud.githubusercontent.com/assets/1912426/14680605/af47ae4e-06d2-11e6-8bab-98315a94d639.jpg)
So each place you see the e and the f that is data that is incorrect.  Newer versions of xEdit do it correctly while people in the past made changes to OMOD records when we asked them not to because it was still being worked on.  Also I only recently updated the Weapon records and I have not finished with the Armor records.

As far as OMOD goes, I can fix plugins with the new version of xEdit or I can make copies of other records with the new version and it works fine.  However, mods still being made or that were made with older versions that have that issue could make xEdit have that exception.

Also keep in mind the CK will fix minor stuff like that.  So once the CK is released mods can be saved with the CK and then you can further look at the plugins in xEdit to see what changed if anything.  Also keep in mind a current theme is for people to post that in the old version of xEdit showed values one way while the new version show it another way.  Once the CK is out, what we put in the record is what it should be.

Exceptions could be caused by development of plugins with our tool while it was in alpha or something might seem like an issue or discrepancy now but won't be later on.  I think this is a good thing to watch for but it's probably going to resolve itself as long as authors update their mods with the CK.

**Comment by Yagisan** [comment] 2016-04-22 13:56
My understanding of an Access Violation on Windows is that the program is trying to read or write to memory it should not be accessing. While it probably is caused by invalid data, do you think it might be possible to do a sanity check to ensure it isn't trying to do these errant reads and writes ? I'd personally prefer a more graceful failure on garbage input, that allows me to close without crashing.

**Comment by zilav** [comment] 2016-04-22 17:17
AV means that something went wrong, at this point closing without crashing, with crashing, or just terminating with task manager doesn't have a difference.

**Comment by zilav** [comment] 2016-05-31 15:43
Couldn't replicate any issues with ARMO.

**Closed by zilav** 2016-05-31 15:43 UTC
