### ISSUE TITLE
Conflict colors are not refreshed when filter is re-applied

### ISSUE THREAD

**Issue by thelapdragon** [TES5Edit/TES5Edit#1240] opened 2023-11-04 04:27 UTC
**What is the version of xEdit you are using?**
SF1Edit 4.1.4w EXTREMELY EXPERIMENTAL (RC6 for 4.1.5) x64 (CEBBD766)

**Describe the bug**
If you apply a blank filter to the plugins so that xEdit will conflict colorize them, it does so, but if you remove and re-apply the filter, it does not re-colorize new or resolved conflicts - it just reuses the previous colors.

**To reproduce**
1. Load all plugins
2. Apply a filter with no filters enabled, so that all xEdit does is apply conflict coloring.
3. Resolve or create a conflict that changes the color of a form - it won't change the tree color (which is known), but it does update the record colors in the form itself.
4. Clear the existing filter
5. Re-apply the filter you applied in step 2
6. Go to the record that you modified in step 3
7. Observe that the tree color coding for the plugin or tree records have not changed to reflect the new conflict status, even though the form values are still displaying the correct color.

**Expected behavior**
The tree coloring should update after a filter refresh to show accurate conflict coloring - optimally it would update inline as conflicts are adjusted (as xEdit used to do), but I understand that is a project for later.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ElminsterAU** [comment] 2023-11-04 13:09
Can't reproduce. PLEASE, as I said originally, provide actual, step by step instructions that can be used to reproduce the error. Your fail at "1. Load all plugins" already. I can't possibly know what your setup is. Which modules do you have? Your instructions should start with assuming only the official files being present and provide any further files that are required to make the error occur. Then, which record do you edit? how do you edit them? What EXACTLY happens, how do you think it EXACTLY differs from what should happen?...

I created a new module by copy as override a record from Starfield.esm. I applied a filter, I made changes to that record, the left-hand tree view updates instantly as it should... and now?

**Comment by thelapdragon** [comment] 2023-11-05 01:44
The plugins in question did not matter, which is why I didn't specify them - for my testing I started with no modules or plugins at all loaded (aside from the vanilla ones), and then made two plugins with a single record override from the base starfield.esm, and then introduced a conflict by changing a value in the first loaded plugin (mod1.esm in this case).  I've done this several times, with different form and record types, it hasn't mattered what variables I change in the experiment, I always end up with a conflict (as expected) with coloring that matches the expected coloring (as expected), but resolving the conflict does not update the tree view coloring until I completely close out xEdit and reopen it.

I've included the two plugins that I made to test with, and an archive of pictures detailing the steps I take.

1) no filters.png - xEdit right after having been started and I've navigated to the single record in my test .esms
2) filter details.png - the filter I'm using - as you can see there's no record filtering being applied, it's just color-coding the tree view.
3) filter applied 1.png - I've let the filter run, and it's color-coded the tree view.
4) conflict resolved.png - I've resolved the conflict, and the tree view is still red (as expected).
5) filter removed.png - I've removed the filter, the tree view is no longer colored, however the forms are still showing conflict colors.
6) filter applied 2.png - I've re-applied the filter from "filter details.png", and the tree view still shows the conflict colors from filter applied 1.png, even though the conflict is gone in the record detail view.
7) xEdit reopened.png - I've closed and reopened xEdit, and re-applied the same filter again - this time the tree coloring is updated.

[test_plugins.zip](https://github.com/TES5Edit/TES5Edit/files/13258047/test_plugins.zip)
[xEdit_display_bug.zip](https://github.com/TES5Edit/TES5Edit/files/13258077/xEdit_display_bug.zip)

**Comment by thelapdragon** [comment] 2023-11-05 02:54
Update - I've tried with the 4.1.5 version, and also tried fixing the conflict before even running the filter, it still retains the conflict color until xEdit is restarted entirely.  I've also had a friend try it following the directions I posted in this report, and he has confirmed that it happens to him too.

**Comment by ElminsterAU** [comment] 2023-11-05 06:17
Should be fixed with the commit referenced above. Included in xEdit 4.1.5a, which has been posed in #xedit-builds on the xEdit Discord.

**Closed as completed by ElminsterAU** 2023-11-05 06:17 UTC
