### ISSUE TITLE
Access Violation in SSEEdit when saving

### ISSUE THREAD

**Issue by DarthVitrial** [TES5Edit/TES5Edit#661] opened 2019-03-02 16:36 UTC
**What is the version of xEdit you are using?**
4.0.1n (the 32 bit version)

**Describe the bug**
Access violation popup when saving.

**To reproduce**
I opened Missing Encounter Zones, All Exteriors in SSEEdit, manually removed a record  (the ownership record at NightingaleHallExterior [CELL:0000BD33] (in Tamriel "Skyrim" [WRLD:0000003C] at 42,-27)
Block 1,-1 --> Sub-Block 5, -4). Then I hit ctrl-s and saved.

**Expected behavior**
A save.

**Additional context**
Here's the exception log: https://pastebin.com/wc3aLKh2

**Comment by ElminsterAU** [comment] 2019-03-03 03:37
Are you sure that it didn't actually save? Because while the exception shows a crash that needs to be fixed, that crash is from inside the repainting of the treeview and should not affect the ability to save.

**Comment by DarthVitrial** [comment] 2019-03-03 03:51
Yes, that’s my bad. It saved just fine.

**Comment by ElminsterAU** [comment] 2019-03-03 03:53
Ok, thanks for confirming. I have a theory about what could be the cause of the crash in the nav tree view update (though I have been unable to reproduce it myself) and will try implementing a fix for it in the next RC

**Comment by ElminsterAU** [comment] 2019-03-12 05:38
This should be fixed in 4.0.2

**Closed by ElminsterAU** 2019-03-12 05:38 UTC
Labels: All Supported Games, bug
