### ISSUE TITLE
Sorting masters does not update references with worldspace/cell records

### ISSUE THREAD

**Issue by clayne** [TES5Edit/TES5Edit#487] opened 2018-07-31 00:57 UTC
For whatever reason I noticed that Beantown Interiors happens to have DLC masters out of order and whilst doing experimental work in CK I noticed severe issues cropping up due to how CK saves the master entry order vs the references that obviously depend on this. I attempted to rectify the issue in xEdit by sorting masters (which I've done before on simpler plugins without issue) and afterward a check for errors resulted in probably a 100+ errors about bad references.

Every single error was trivially recognizable by the fact that a cell reference would refer to the same refid as it was prior to the sort. This would happen to navmesh entries, worldspace pointers for cells, basically anything that was dependent on the master order. I started to fix them manually by about the 40th one in I realized "why am I doing this?" Clearly the tool is capable of updating references during a master sort, so why isn't that applying to various records under worldspace?

The reason this is a problem is a: the tool knows how to resolve this already, b: fixing it manually is extremely tedious, c: CK (atleast in 2.x, not sure about older) is always going to re-sort, prune, or otherwise modify master order when a plugin is saved. I realize it's on the mod author to fix this, but ponder how said author would even go about fixing this in xEdit, let alone CK.

**Comment by Sharlikran** [comment] 2018-07-31 04:05
This is similar to #208

**Comment by zilav** [comment] 2018-07-31 04:41
Right after sorting masters save plugin and reload, then check for errors. xEdit sometimes is not updating additional elements after sorting, however they are "fake" ones not stored in plugins, and reloading fixes that.

**Comment by Sharlikran** [comment] 2018-07-31 05:13
Better yet, post a screen shot of xEdit with it open please and one of the records selected. A Full size screen shot please.

**Comment by eFrysTon** [comment] 2018-07-31 05:16
I'm pretty sure zilav is right and these are the virtual elements that get added to a record in a children of group which show the group label

**Comment by clayne** [comment] 2018-07-31 06:03
The mode this is in is fo4edit and I just tried it after saving out after a master re-sort and it checks out fine. This still seems like a bug though, guys. A potentially mod breaking operation shouldn't require a save and reload just to check that it went well. Sure there's always backups but certainly there should be some kind of plugin reload operation or condition that gets triggered by things known to require that and it seems like that codepath basically just isn't there right now.

I've also noticed similar funky behavior with this when doing things like removing a master from the file header manually and then doing a sort masters which lead to an assertion failure.

**Comment by eFrysTon** [comment] 2018-07-31 06:17
a) neither zilav nor I said this is not a bug. Just that it has 0 effect on the validity of the module you are editing. The virtual elements in question should be invalidated, so that they will recalculate their cached value the next time they are being accessed, also they shouldn't even participate in error reporting at all.

b) never, never, never, never ever modify the MAST sub-records in the file header directly except if you know 1000% exactly what you are doing. Doing so is pretty much guaranteed to break your files.

Making changes to the file header directly will NOT update any of the FormIDs stored inside the file (which are file specific FormIDs that are being resolved to load order corrected FormIDs using exactly the MAST sub-records in the file header). Making changes to the file header directly will change the meaning of all file FormIDs that have an upper byte equal or higher than the index of the MAST subrecord you just deleted.

**Comment by Sharlikran** [comment] 2018-07-31 06:35
>  when doing things like removing a master from the file header manually and then doing a sort masters which lead to an assertion failure.

I always use clean masters instead of manually removing masters. Hopefully I'm not repeating what Elminster said exactly, but... I don't remove them that way because any records in use that belonged to the master end up with the error `< Error: Could not be resolved >` instantly. More so once you then sort masters with any potentially broken references are basically pointing to NULL now.  In that case an AV should be expected. How can you renumber 0111C6C7 to 0211C6C7 when neither FormID exists.

As long as I am reading your steps correctly.

1. Remove Master manually (irrespective of whether or not records are in use)
2. Sort Masters
3. AV occurs as a result.

If you want to remove the master, although not recommended without using clean masters at least apply the script "List records referencing specific plugin.pas" to see if anything references the master.

I understand your point that there should be some kind of plugin reload operation or condition that gets triggered. As long as there are no changes to the list of masters in the header I'll make as many changes as I want.  However, I save any time masters are added or removed. Simply because of what Elminster said in B.

**Comment by clayne** [comment] 2018-07-31 23:12
I completely understand the risk of manually altering the master records in the file header. I wasn't doing it without care, I was doing it strategically to work around CK implicitly clipping unused master entries (basically "clean masters") on save but I wanted those master entries retained. The entire purpose of the plugin I was using was to simply to get CK to load a set of masters for me which I was using for an experiment related to multi-master precombine generation. For whatever reason I did it manually as the initial plugin was empty and had no risk of refids getting trashed/redirected and had added one too many masters with the normal "add masters" command. That's why I couldn't just use "clean masters" right there as it would remove a bunch of masters I wanted the plugin to retain for my experiment - hence the manual removal.

As far as the assertional violation goes, I think the only thing I did different was simply "sort masters" after my manual removal.

It seems like the real issue here is that there are certain operations which can be done to masters (e.g. file header) that will result in xEdit's idea of what masters are in use being out of sync with reality (or future reality for that matter).

I'll try 3.2.3v out. The version I'm using is 3.2.1 I believe (whatever is on Nexus).

**Comment by eFrysTon** [comment] 2018-08-01 03:09
Let me repeat once more, once you touch the MAST subrecords in the file header, all bets are off. You are now hanging with your pinky from the middle of a 1km tightrope over a 10km chasm. 

The fact that you so cavalier talk about making changes to these subrecords and "not doing it without care" seems to me to strongly indicate that you do not in fact understand the implications of what you are doing.

If you truly understood what you are doing, you would understand that the moment you edited that MAST subrecord, the only thing you could possible do is close xEdit and save the file before navigating away from it.

Seeing that people simply can't behave responsible, I'll completely disable direct editing of MAST subrecords.

**Comment by clayne** [comment] 2018-08-03 01:30
> Let me repeat once more, once you touch the MAST subrecords in the file header, all bets are off. You are now hanging with your pinky from the middle of a 1km tightrope over a 10km chasm.
>
> The fact that you so cavalier talk about making changes to these subrecords and "not doing it without care" seems to me to strongly indicate that you do not in fact understand the implications of what you are doing.

Right, but you're not listening to the part where I *created the _empty_ plugin myself entirely for the purpose of forcing CK to load the masters*. This is not some random plugin that I'm just hacking masters around in, I was doing it on purpose. The entire purpose of doing this was to force CK to load dependent plugins for which I was generating combined data for. The whole MAST thing only came up because I simply removed an entry that was errantly added with the "add masters" window because if I used "clean masters" it would basically remove a bunch of ESPs I just added. On top of that whole thing was simply an experiment anyway. I wasn't looking for handholding I was looking for understanding on why the tool was functioning that way. If I want to break my own stuff I'm free to do that and I do not expect support from you on that. On top of that, none of that is even relevant because the exact same issue is still an issue for "sort masters."

> If you truly understood what you are doing, you would understand that the moment you edited that MAST subrecord, the only thing you could possible do is close xEdit and save the file before navigating away from it.

As far as the MAST subrecord goes there's zero reason to remove functionality for something that has a functional purpose. You're basically arguing "I'm going to remove this because I don't think people know how to use it" when in reality the real issue here is the virtual references created by xEdit after a master operation are not being entirely reflected back to all dependent cells in a way that is visible to the UI after that point (or simply because the plugin wasn't reparsed). That's a bug whether you like it not and that same bug will be there even if you stopped users from "not behaving responsibly" (not really a developer's call to make btw) because it affects "sort masters" just the same.

> Seeing that people simply can't behave responsible, I'll completely disable direct editing of MAST subrecords.

Now as far as all the other stuff I think you're jumping the gun a bit in your assumption of my knowledge about how the plugins actually work and that I'm some idiot randomly changing things trying to get something to work. My approach, method, or what my actual motive was isn't even the issue here, the issue here is that I ran into something acting non-intuitively and brought it up. Judging by the previous issue referenced in the first response said issue was also brought up in the past too. "Save and quit xEdit and reload - then things are fine after" isn't an actual fix, it's a workaround. If the solution to that is crippling or removing functionality the tool then I don't know what to tell you.

**Comment by RoyBatty64** [comment] 2018-08-03 01:38
The way to handle the situation is to clean masters, save, reload with your other plugins selected, add masters, sort masters, save reload and do your edits then.

He was trying to explain that your method was wrong because of how indexes are built off the master list in the header. Removing one of them will create a gap in the index which are already built and create and error on reloading the plugin. That's not a bug in xEdit, it's by design and exactly how the game does it.

**Comment by clayne** [comment] 2018-08-03 02:14
I get it, the master list order and a plugin's internal references are obviously incredibly important to each other and that masters can't just be willy nilly screwed with without dependent refs breaking as the form ids are order/index dependent. My entire point was that *sort masters* is already doing this and requiring the user to save the plugin and exit back out just to see this reflected in records is an issue in itself - unless you're telling me there's something magical about quitting xEdit and restarting it that makes it now able to do what it could have already done after a master modification without the whole save/close/reload schtick?

To be honest, it's not even that big a deal to me if the workaround is simply save out and reload - but trying to argue that the behavior isn't questionable seems a bit off. This is what I am saying: let's pretend we have a function called plugin_master_update() after the master list is modified and that said function saves the current plugin, quits xedit, and restarts xedit with the same plugin reloaded. 99/100 developers would look at that and say "wtf? why not just do that in the code" would they not?

**Comment by eFrysTon** [comment] 2018-10-01 01:09
should be fixed with the commit referenced above

**Closed by eFrysTon** 2018-10-01 01:09 UTC
Labels: FO4Edit, bug
