### ISSUE TITLE
Commandline parameter processing seems to be broken

### ISSUE THREAD

**Issue by siaccarino** [TES5Edit/TES5Edit#693] opened 2019-04-20 11:17 UTC
**What is the version of xEdit you are using?**
TES5Edit 4.0.2 (F796EF8E)

**Describe the bug**
It seems that xEdit ignores any commandline parameter - I can't load modules and start scripts and maybe the issue #692 is also caused by this issue
Commandline parameters taken from:
https://wiki.step-project.com/Guide:XEdit#Launch_Arguments

**To reproduce**
1. Put anything on commandline
3. Open xEdit
4. Nothing happens

**Expected behavior**
Commandline parameters getting executed

**Comment by Sharlikran** [comment] 2019-04-20 22:18
So I will be closing this because this is for issue reports and not observations of functionality. Our issues section is not a forum. Please join discord for now since the comments sections are closed due to user comments.

As far as loading xEdit and using a script this is not a bug you are simply doing it wrong. The command line arguments do not affect the scripts. You also have not communicated which script. We do not support any scripts that do not come with the download. So anything else from anyone else you will need to contact them.

**Closed as completed** 2019-04-20 22:21 UTC
Labels: invalid
