### ISSUE TITLE
Bleakwind basin added to plugin while cleaning

### ISSUE THREAD

**Issue by yggdrasil75** [TES5Edit/TES5Edit#669] opened 2019-03-17 15:45 UTC
**What is the version of xEdit you are using?** 
SSEEdit 4.0.1 (40732B8C) starting session 2019-03-17 11:38:08

**Describe the bug**
When Cleaning a plugin with worldspace edits (have noticed in other plugins, just didnt pay attention to when it was added) the bleakwindbasinexterior worldspace is copied into the plugin.

**To reproduce**
make a plugin that moves or marks something (ie: a bush or crate) as deleted and use `-quickautoclean` to make the edit a proper disabling of the item instead of a deletion

**Expected behavior**
undelete and disable records marked as deleted, and remove itms.

**Screenshots**
before cleaning
https://cdn.discordapp.com/attachments/495404330535485460/556862012685156352/unknown.png
after cleaning
https://cdn.discordapp.com/attachments/495404330535485460/556862024190001165/unknown.png

**Additional context**
included files: the backup is before the edit, the one without backup is after cleaning. plugin requires moon and star sse and t'skyrim riverwood.

[cleaning error.zip](https://github.com/TES5Edit/TES5Edit/files/2975359/cleaning.error.zip)

**Comment by Sharlikran** [comment] 2019-03-18 02:41
@ElminsterAU whether or not it resolves this, shouldn't he update to 4.0.2 anyway? Any possible fix you make will be in 4.0.2s code anyway.

**Comment by ElminsterAU** [comment] 2019-03-18 04:26
Yes, 4.0.2 should be the basis for any bug reports now.

**Comment by ElminsterAU** [comment] 2019-03-18 04:27
@yggdrasil75  please check that you can reproduce this with 4.0.2.

**Comment by Spawnkiller** [comment] 2019-03-18 21:37
@ElminsterAU hi, I just reproduced the effect of Bleakwind Basin add in after QAC at a plugin of mine. This time with TES5edit version 4.0.2. It happened after I carried over only one new reference into my plugin and flagged the record as deleted in regular mode (no start parameter). Saved it and then reopened tes5edit with qac option -> bingo. It looks like an vanilla record from HearthFires.esm.
The mod my patch is for (AnnaWinderhold.esp) has also this BleakwindBasinExteriro01 entry, beside it does not touch this area at all (it only touches winterhold exterior and interior world space.

**Comment by Arthmoor** [comment] 2019-03-19 00:39
This looks like the sort of thing that might happen when a deleted record is being undeleted and has a temporary step where it's restored to full status before being removed - but somehow the resulting Bleakwind Basin edit gets left behind since it's the default 0,0,0 origin point for Tamriel.

I ran into this with some other mod not long ago but have forgotten what it was and thought it a fluke since it hasn't happened again with anything else.

**Comment by ElminsterAU** [comment] 2019-03-19 03:25
@Spawnkiller can you please provide that file and links for any dependencies? TIA!

**Comment by ElminsterAU** [comment] 2019-03-19 03:26
@Arthmoor that's pretty much what I'm thinking too. I just need to reproduce it under the debugger to find the code that's responsible for creating that CELL record.

**Comment by Spawnkiller** [comment] 2019-03-19 19:59
I tested it again today with SSEEdit:
The unwanted add in of BleakwindBasinExterior01 [CELL000099A2] only happens if I carry over a new reference form the source plugin and flag it deleted. If I flag an existing record in my plugin (a total new one not part of the source) deleted and QAC it, BleakwindBasinExterior01 [CELL000099A2] was not added.

To test you need Anna's Winterhold Restored SE “https://www.nexusmods.com/skyrimspecialedition/mods/20344"

my bug fix plugin (only for demonstration, not for public release it as it only my shows my findings and fixes of  bugs and improvements of the her mod, just to show her my findings, it’s up to her to in cooperate it into her creation or not.) 
A zip with 3 files the virus stages of the same plugin:
1-	“vanilla” without new reference
2-	Carried over a new reference flagged as deleted
3-	QAC plugin with unwanted Bleak add in reference 

I put a password in the zip and will pm it to you in discord.
[20190319_QAC_Bug_hunt.zip](https://github.com/TES5Edit/TES5Edit/files/2985371/20190319_QAC_Bug_hunt.zip)


Procedure is true and result is the same for a TES5Edit plugin.

**Comment by Ralgor** [comment] 2019-03-21 01:07
I was able to get this to fail as well. I actually copied a random reference from Skyrim.esm into a new plugin, then marked it deleted. Reloaded xedit, and without using QAC, just applied the filter for cleaning and clicked on UDR. After removing the filter, the rogue cell appeared.

**Comment by Ralgor** [comment] 2019-03-21 01:37
Forget using UDR. Just removing the Delete flag from the record will cause the rogue cell to appear.

**Comment by ElminsterAU** [comment] 2019-03-21 19:16
xEdit 4.1.2c EXTREMELY EXPERIMENTAL in #xedit-builds on the Discord should fix this. Please confirm.

**Comment by eFrysTon** [comment] 2019-10-10 04:18
is fixed with commit referenced above

**Closed** 2019-10-10 04:19 UTC
Labels: SSEEdit
