### ISSUE TITLE
Old TES4LODGen bug with 3.2.70 and 3.2.71

### ISSUE THREAD

**Issue by Supierce** [TES5Edit/TES5Edit#558] opened 2018-10-02 03:28 UTC
3.2.71

With 3.2.70 and 3.2.71 the old TES4LODGen inability to generate LOD with TWMP_Valenwood_Elsweyr.esp has returned after having been fixed for several years. Whenever TWMP_Valenwood_Elsweyr.esp is active in the load order, there's a solid hang about a third of the way through Tamriel generation. This is true even when it's the only mod loaded (along with its master, Tamriel.esp). Builds 3.2.2 and earlier work fine with that same mod.

**To Reproduce**
Rename xEdit 3.2.70 or 3.2.71 to TES4LODGen. In Oblivon, install Tamriel.esp and TWMP_Valenwood_Elsweyr.esp. Run TES4LODGen.

**Expected behavior**
LOD Generation should complete with no hang..

**Comment by Sharlikran** [comment] 2018-10-04 02:00
@Project579#3715 There is a (one) actual dev Utumno but he is just refactoring code. I tried experimenting with patchers, hacking up the code, adding things, improving things, and whatever to make it useful. Don't get me wrong the refactoring is making the program run really well and it needed but from a user standpoint nothing was changing.

My main thing is decode decoding the same as with xEdit. But I'm experimenting and trying to learn more python.

My current changes add >255 plugin support if you have esl flagged files, patching esl flagged files, toggle esl flag, and I'm fi fishing up with a check to keep people from flagging a plugin with >$FFF forms.

**Comment by eFrysTon** [comment] 2018-10-04 03:53
Please provide a link where I can find the mod in question.

**Comment by Sharlikran** [comment] 2018-10-04 04:07
@Supierce 
Specifically can Elminster have a link to both `Tamriel.esp` and `TWMP_Valenwood_Elsweyr.esp` downloads. Neither of us frequent other websites like TAL and wouldn't know where to find those. To troubleshoot this we would also need all required masters. Is Elsweyr still available?

**Comment by Supierce** [comment] 2018-10-04 15:57
@Sharlikran, I apologize - I should have included those links.

You don't need Elsweyr or other TWMP mods, just the three Valenwood_Elsweyr files from here:

https://www.nexusmods.com/oblivion/mods/38792?tab=files

...and the master, Tamriel.esp, from Tamriel heightmap V_3_3:

https://www.nexusmods.com/oblivion/mods/27235/?tab=files

Let me know if you need anything else. Thanks!

**Comment by Sharlikran** [comment] 2018-10-04 23:01
Last thing what is your mod manager? MO2 or strictly Wrye Bash? Sometimes NMM or what?

**Comment by Sharlikran** [comment] 2018-10-04 23:45
> Rename xEdit 3.2.70 or 3.2.71 to TES4LODGen. In Oblivon, install Tamriel.esp and TWMP_Valenwood_Elsweyr.esp. Run TES4LODGen.

That's hilarious as I had not gone to either link searching for those. Don't change your original question but I have to ask something. I do need `TWMP_Valenwood_Elsweyr.esp` installed and `Tamriel.esp` to test this and you say I don't need Elsweyr. Yet `ElsweyrAnequina.esp` is a master of `TWMP_Valenwood_Elsweyr.esp`.

So I have some links but still only have some idea of what to install. I have never played Oblivion and don't know if I have the right files or links.

So for your instructions please do something like this:

From Link Blah download:

Valenwood_Elsweyr esp-38792-0-1.rar
Valenwood_Elsweyr Resources bsa-38792-01.rar
Valenwood_Elsweyr Lod Resources-38792.rar

Install all three

From Link Blah download:

Tamriel heightmap V_3_3-27235.rar
Tamriel Heightmap LOD Resources-27235.rar

Install those two

From Link Blah download:

Elsweyr Anequina Mar 2014.rar
ElsweyrAnequinaMeshesTextures.rar

Install those two.

Now with Elsweyr Anequina there are 5 files so which do I need to install in Wrye Bash in which order to make all the fixes work? Because there are LOD fiix files and it would make sense I need them.

![image](https://user-images.githubusercontent.com/1912426/46508830-37634380-c7f4-11e8-8218-304c776a35fc.png)

My question now is which `ElsweyrAnequina.esp` do I need? Is there the March 2014 version and a new version? Which it the patch based off of. Because I have to have the correct files.

**Comment by Supierce** [comment] 2018-10-05 11:40
Yes, I missed that - apologies again! I'm using the newer version of ElsweyrAnequina.esp.

**Comment by eFrysTon** [comment] 2018-10-05 11:57
Could you please provide clear step by step instructions going from a vanilla Oblivion setup to whatever is required to reproduce the problem you are seeing? TIA.

**Comment by Supierce** [comment] 2018-10-05 17:44
1. To the vanilla Oblivion setup, install Tamriel.esp,  ElsweyrAnequina.esp, and Valenwood_Elsweyr esp, in that order. I use Wrye Bash, but installing manually or using another installer should work as long as the load order is right.
2. Rename SSEEdit 3.2.71 to TES4LODGen and copy to the main Oblivion folder.
3. Run TES4LODGen to generate DistantLOD files for all of Tamriel.
4. In my case, at around 42% complete, LOD generation stops no matter how long it's left to run. It's a bug from several years ago that is fixed in all xEdit builds through 3.2.2, but returned in 3.2.70.
Let me know if you need something more specific. Thanks!

**Comment by Supierce** [comment] 2018-10-05 20:34
I keep failing to anticipate what you guys need and I should know better. Here it is:

http://www.theassimilationlab.com/forums/files/file/1070-elsweyr-anequina/

There's only one download and it's the updated one.

**Comment by Sharlikran** [comment] 2018-10-05 22:16
I had the right link but didn't know what the filename was. I cant see the site from my phone. I'll check when I get home. There are 5 files though.

**Comment by Sharlikran** [comment] 2018-10-06 03:05
# Test with 3.2.2

I was able to build the LOD with 3.2.2 looking to see if another older version works so I can track down the commit that changed things.

**Comment by Sharlikran** [comment] 2018-10-06 05:42
[TES5Edit_3.2.53.zip](https://github.com/TES5Edit/TES5Edit/files/2452771/TES5Edit_3.2.53.zip)

@Supierce that is the last version that seems to work, and once there is a newer version I'll let you know

**Comment by zilav** [comment] 2018-10-06 07:12
Some Oblivion worldspace plugins are broken iirc, they have garbade data in Pos\Rot of references or even missing DATA subrecord completely (I suspect a bug in TES4Gecko). I think the best way is to try/except and ignore such refs when building LOD as fixing those plugins is not an option. They are too large and authors have left modding for good.

Maybe even add a new wbIgnoreFloatErrors option to not show float errors and set it when running in LODGen mode.

**Comment by eFrysTon** [comment] 2018-10-07 00:34
The issue in this case isn't with writing the error messages (it's only a couple of screens full) but with the fact that I replaced exception handling with masking FPU exceptions and later checking the FPU exception flags during the reading of the floats (to prevent the high performance cost of raising exceptions).

This resulted in an endless loop in RadiansNormalize which would normally have been terminated by an exception.

**Comment by Sharlikran** [comment] 2018-10-07 06:14
[TES4LODGen.zip](https://github.com/TES5Edit/TES5Edit/files/2453657/TES4LODGen.zip)

This is the current version with the fix. I tested it already and it works just fine. The plugin still has errors that should be resolved in the CK as the float is invalid so you can't display the invalid part of it and then see it in TES4Edit and correct it. It's invalid so it probably won't show it, or it will say None or something.

I just don't want the author to say xEdit is broke, it's not. Those are existing errors.

**Comment by Supierce** [comment] 2018-10-07 14:47
Yes, it works fine. Thank you - I really appreciate all that you guys do!

**Comment by eFrysTon** [comment] 2018-10-09 09:52
should be fixed with the commit referenced above

**Closed by eFrysTon** 2018-10-09 09:52 UTC
Labels: TES4Edit, bug
